// ============================================================================
// Module: spikegambit_top
// Description: Complete SpikeGambit SCNN accelerator with Clocking Wizard
//              Physical Input: 100 MHz (ZedBoard Y9)
//              Internal Clock: 75 MHz (generated by MMCM)
//              Top-level port named 'clk_75mhz' to match XDC constraints.
// ============================================================================

module spikegambit_top (
    input  wire clk_75mhz,     // 100 MHz physical input from ZedBoard (pin Y9), named clk_75mhz to match XDC
    input  wire rst_n,         // Active-low reset
    
    // Input interface
    input  wire input_spike,
    input  wire [3:0] input_channel,
    input  wire [2:0] input_x,
    input  wire [2:0] input_y,
    input  wire input_valid,
    
    // Output interface
    output wire [0:0] predicted_class,
    output wire output_valid,
    output wire busy
);

    // ========================================================================
    // Clock Generation: 100 MHz (clk_75mhz port) -> 75 MHz via Clocking Wizard
    // ========================================================================
    wire clk_75mhz_gen;
    wire clk_locked;
    
    clk_wiz_0 clk_wizard_inst (
        // Clock out ports
        .clk_out1(clk_75mhz_gen),   // output clk_out1 (75 MHz)
        // Status and control signals
        .reset(~rst_n),             // input reset (active high, so we invert rst_n)
        .locked(clk_locked),        // output locked
        // Clock in ports
        .clk_in1(clk_75mhz)         // input clk_in1 (100 MHz physical)
    );
    
    // Only run logic when the generated clock is stable and locked
    wire sys_clk = clk_75mhz_gen;
    wire rst_n_internal = rst_n & clk_locked;
    // ========================================================================
    // Internal wires (scaled-down network: 12->16->32->64)
    // ========================================================================
    wire conv1_spike;
    wire [3:0] conv1_channel;
    wire [2:0] conv1_x, conv1_y;
    
    wire conv2_spike;
    wire [4:0] conv2_channel;
    wire [1:0] conv2_x, conv2_y;
    
    wire conv3_spike;
    wire [5:0] conv3_channel;
    wire [0:0] conv3_x, conv3_y;
    
    // Weight memory interfaces
    wire [11:0] conv1_weight_addr;
    wire signed [15:0] conv1_weight_data;
    
    wire [14:0] conv2_weight_addr;
    wire signed [15:0] conv2_weight_data;
    
    wire [16:0] conv3_weight_addr;
    wire signed [15:0] conv3_weight_data;
    
    // Control signals
    wire conv1_busy, conv2_busy, conv3_busy;
    wire classifier_busy;
    
    assign busy = conv1_busy | conv2_busy | conv3_busy | classifier_busy;
    
    // ========================================================================
    // Layer 1: Conv1 (12 -> 16 channels, 8x8 board)
    // ========================================================================
    weight_memory #(
        .DATA_WIDTH(16),
        .ADDR_WIDTH(12),
        .DEPTH(4096),
        .FILE_NAME("../../ml/quantization/verilog_weights/conv1_weights.mem")
    ) conv1_weights (
        .clk(sys_clk),
        .read_addr(conv1_weight_addr),
        .read_data(conv1_weight_data),
        .read_en(1'b1)
    );
    
    conv_layer #(
        .IN_CHANNELS(12),
        .OUT_CHANNELS(16),
        .BOARD_SIZE(8),
        .DATA_WIDTH(16),
        .WEIGHT_ADDR_WIDTH(12),
        .IN_CHANNEL_WIDTH(4),
        .OUT_CHANNEL_WIDTH(4),
        .XY_WIDTH(3)
    ) conv1 (
        .clk(sys_clk),
        .rst_n(rst_n_internal),
        .in_spike(input_spike),
        .in_channel(input_channel),
        .in_x(input_x),
        .in_y(input_y),
        .weight_addr(conv1_weight_addr),
        .weight_data(conv1_weight_data),
        .out_spike(conv1_spike),
        .out_channel(conv1_channel),
        .out_x(conv1_x),
        .out_y(conv1_y),
        .busy(conv1_busy)
    );
    
    // ========================================================================
    // Layer 2: Conv2 (16 -> 32 channels, 4x4 board)
    // ========================================================================
    weight_memory #(
        .DATA_WIDTH(16),
        .ADDR_WIDTH(15),
        .DEPTH(32768),
        .FILE_NAME("../../ml/quantization/verilog_weights/conv2_weights.mem")
    ) conv2_weights (
        .clk(sys_clk),
        .read_addr(conv2_weight_addr),
        .read_data(conv2_weight_data),
        .read_en(1'b1)
    );
    
    conv_layer #(
        .IN_CHANNELS(16),
        .OUT_CHANNELS(32),
        .BOARD_SIZE(4),
        .DATA_WIDTH(16),
        .WEIGHT_ADDR_WIDTH(15),
        .IN_CHANNEL_WIDTH(4),
        .OUT_CHANNEL_WIDTH(5),
        .XY_WIDTH(2)
    ) conv2 (
        .clk(sys_clk),
        .rst_n(rst_n_internal),
        .in_spike(conv1_spike),
        .in_channel(conv1_channel),
        .in_x(conv1_x[2:1]),
        .in_y(conv1_y[2:1]),
        .weight_addr(conv2_weight_addr),
        .weight_data(conv2_weight_data),
        .out_spike(conv2_spike),
        .out_channel(conv2_channel),
        .out_x(conv2_x),
        .out_y(conv2_y),
        .busy(conv2_busy)
    );
    
    // ========================================================================
    // Layer 3: Conv3 (32 -> 64 channels, 2x2 board)
    // ========================================================================
    weight_memory #(
        .DATA_WIDTH(16),
        .ADDR_WIDTH(17),
        .DEPTH(131072),
        .FILE_NAME("../../ml/quantization/verilog_weights/conv3_weights.mem")
    ) conv3_weights (
        .clk(sys_clk),
        .read_addr(conv3_weight_addr),
        .read_data(conv3_weight_data),
        .read_en(1'b1)
    );
    
    conv_layer #(
        .IN_CHANNELS(32),
        .OUT_CHANNELS(64),
        .BOARD_SIZE(2),
        .DATA_WIDTH(16),
        .WEIGHT_ADDR_WIDTH(17),
        .IN_CHANNEL_WIDTH(5),
        .OUT_CHANNEL_WIDTH(6),
        .XY_WIDTH(1)
    ) conv3 (
        .clk(sys_clk),
        .rst_n(rst_n_internal),
        .in_spike(conv2_spike),
        .in_channel(conv2_channel),
        .in_x(conv2_x[0]),
        .in_y(conv2_y[0]),
        .weight_addr(conv3_weight_addr),
        .weight_data(conv3_weight_data),
        .out_spike(conv3_spike),
        .out_channel(conv3_channel),
        .out_x(conv3_x),
        .out_y(conv3_y),
        .busy(conv3_busy)
    );
    
    // ========================================================================
    // Output Classifier
    // ========================================================================
    output_classifier #(
        .NUM_CLASSES(2),
        .TIME_STEPS(200),
        .DATA_WIDTH(16),
        .CLASS_ID_WIDTH(1)
    ) classifier (
        .clk(sys_clk),
        .rst_n(rst_n_internal),
        .spike_in(conv3_spike),
        .class_id(conv3_channel[0]),
        .input_valid(conv3_spike),
        .predicted_class(predicted_class),
        .output_valid(output_valid),
        .start(input_valid),
        .busy(classifier_busy)
    );

endmodule